import { expect, test } from '@playwright/test'

test('Phase 2: parsers, extra fields, tolerant failures, views, reparse and mobile', async ({ page }) => {
  const errors: string[] = [], uploads: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.method() === 'POST') uploads.push(request.url()) })
  await page.goto('/')
  const parser = page.getByRole('combobox', { name: 'Parser', exact: true })
  const picker = page.getByLabel('Replace or import log file')
  await parser.selectOption('jsonl')
  await picker.setInputFiles({ name: 'events.jsonl', mimeType: 'text/plain', buffer: Buffer.from('{"level":"error","message":"timeout","trace_id":"abc","nested":{"ok":true}}\n{broken}\n\n') })
  const grid = page.getByRole('grid', { name: 'Structured logs' })
  await expect(grid).toBeVisible()
  await expect(grid.getByRole('columnheader', { name: 'trace_id', exact: true })).toHaveCount(1)
  await expect(page.getByText('2 records · 1 failed · 1 skipped')).toBeVisible()
  await grid.focus(); await grid.press('Enter')
  await expect(page.getByLabel('Parsed fields')).toContainText('{"ok":true}')
  await grid.press('ArrowDown')
  await expect(page.getByText(/Parse failed:/).last()).toBeVisible()
  await expect(page.getByLabel('Raw log content')).toHaveText('{broken}')
  await page.getByRole('button', { name: 'Raw', exact: true }).click()
  await expect(page.getByRole('listbox')).toBeVisible()
  await parser.selectOption('plain')
  await expect(page.getByText('0 failed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Structured', exact: true }).click()
  await expect(grid.getByRole('columnheader', { name: 'trace_id', exact: true })).toHaveCount(0)

  await parser.selectOption('csv')
  await picker.setInputFiles({ name: 'events.csv', mimeType: 'text/csv', buffer: Buffer.from('level,status,message\nWARN,400,"bad,\nrequest"\nINFO,200,ok\n') })
  await expect(page.getByText('2 records · 0 failed · 1 skipped')).toBeVisible()
  await grid.focus(); await grid.press('Enter')
  await expect(page.getByLabel('Raw log content')).toHaveText('WARN,400,"bad,\nrequest"')
  await grid.press('End')
  await expect(page.getByLabel('Raw log content')).toHaveText('INFO,200,ok')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/phase2-mobile.png' })
  await page.setViewportSize({ width: 1440, height: 900 })

  await parser.selectOption('access')
  await picker.setInputFiles({ name: 'access.log', mimeType: 'text/plain', buffer: Buffer.from('127.0.0.1 - - [10/Oct/2023:13:55:36 -0700] "GET / HTTP/1.1" 503 200\n') })
  await expect(grid.getByRole('gridcell', { name: '503', exact: true })).toHaveCount(1)
  await parser.selectOption('syslog')
  await picker.setInputFiles({ name: 'syslog.log', mimeType: 'text/plain', buffer: Buffer.from('<34>Jan  1 00:00:00 web sshd[3]: Failed password\n') })
  await expect(grid.getByRole('gridcell', { name: 'CRIT', exact: true })).toHaveCount(1)
  await page.screenshot({ path: 'test-results/phase2-structured.png' })
  expect(errors).toEqual([])
  expect(uploads).toEqual([])
})

test('100K structured records virtualize; cancelled reparse retains old parser', async ({ page }) => {
  test.setTimeout(90_000)
  await page.goto('/')
  const parser = page.getByRole('combobox', { name: 'Parser', exact: true })
  await parser.selectOption('jsonl')
  await page.getByLabel('Replace or import log file').setInputFiles({ name: 'large.jsonl', mimeType: 'text/plain', buffer: Buffer.from('{"level":"INFO","message":"ok","status":200}\n'.repeat(100_000)) })
  await expect(page.getByText('100,000 records · 0 failed · 0 skipped')).toBeVisible({ timeout: 45_000 })
  const grid = page.getByRole('grid', { name: 'Structured logs' })
  await grid.focus(); await grid.press('End')
  await expect(grid.locator('[aria-rowindex="100001"]')).toBeVisible()
  expect(await grid.getByRole('row').count()).toBeLessThan(60)
  // Cancel at first rendered progress state, before this short parse can finish.
  await page.evaluate(() => {
    const observer = new MutationObserver(() => {
      const cancel = Array.from(document.querySelectorAll('button')).find(button => button.textContent === 'Cancel import')
      if (cancel) { observer.disconnect(); cancel.click() }
    })
    observer.observe(document.body, { childList: true, subtree: true })
    const select = document.querySelector<HTMLSelectElement>('select[aria-label="Parser"]')!
    select.value = 'plain'; select.dispatchEvent(new Event('change', { bubbles: true }))
  })
  await expect(page.getByText('Parsing cancelled. Previous dataset kept.')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Cancel import' })).toHaveCount(0)
  await expect(parser).toHaveValue('jsonl')
  await expect(page.getByText('100,000 records · 0 failed · 0 skipped')).toBeVisible()
})
