import { test, expect } from '@playwright/test'
import { writeFileSync } from 'node:fs'

test('Phase 1: health, file import, raw detail, large virtual scroll, cancel and mobile', async ({ page, request }, testInfo) => {
  test.setTimeout(120_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const health = await request.get('http://127.0.0.1:8000/health')
  expect(health.status()).toBe(200)
  expect(await health.json()).toEqual({ status: 'ok' })
  await page.goto('/')
  await page.screenshot({ path: 'test-results/empty-dashboard.png' })
  const picker = page.getByLabel('Replace or import log file')
  await picker.setInputFiles({ name: 'two-lines.log', mimeType: 'text/plain', buffer: Buffer.from('first\nlast\n') })
  await expect(page.getByRole('listbox')).toBeVisible()
  await page.getByRole('option').nth(1).click()
  await expect(page.locator('pre')).toHaveText('last')
  expect(await page.locator('pre').textContent()).toBe('last')

  // 50 MiB exactly: 200K lines; offset storage avoids a string object per row.
  const row = '2026-09-17T10:00:00Z INFO api request completed '.padEnd(261, 'x') + '\n'
  const data = Buffer.alloc(50 * 1024 * 1024, ' ')
  data.write(row.repeat(200_000))
  const started = Date.now()
  const largePath = testInfo.outputPath('large.log')
  writeFileSync(largePath, data)
  await picker.setInputFiles(largePath)
  await expect(page.getByRole('button', { name: 'Cancel import' })).toHaveCount(0, { timeout: 45_000 })
  await expect(page.getByText('200,001', { exact: true })).toBeVisible()
  console.log(`50 MiB import: ${Date.now() - started} ms`)
  const list = page.getByRole('listbox')
  await list.focus()
  await list.press('End')
  await expect(page.locator('#log-line-200000')).toBeVisible()
  expect(await page.getByRole('option').count()).toBeLessThan(60)
  await list.press('Home')
  await expect(page.locator('#log-line-0')).toBeVisible()
  await page.screenshot({ path: 'test-results/loaded-dashboard.png' })

  const oversizedPath = testInfo.outputPath('too-large.log')
  writeFileSync(oversizedPath, Buffer.alloc(50 * 1024 * 1024 + 1))
  await picker.setInputFiles(oversizedPath)
  await expect(page.getByRole('alert')).toContainText('50 MB')
  await picker.setInputFiles(largePath)
  await page.getByRole('button', { name: 'Cancel import' }).click()
  await expect(page.getByRole('button', { name: 'Cancel import' })).toHaveCount(0)
  await expect(page.getByText('200,001', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/mobile-dashboard.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
